spring:
  profiles:
    # active 加上mideaopen的配置文件，才能合并yml
    active: dev

jackson:
  #指定日期格式，比如yyyy-MM-dd HH:mm:ss
  date-format: yyyy-MM-dd HH:mm:ss
  #指定日期格式化时区
  time-zone: UTC

logging:
  file: logs/ac-weather.log
  max-history: 7
  max-size: 100MB
  level:
    com.midea.ac.mideaopen.service.IMideaOpenApi: DEBUG

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

