server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://172.18.0.201/ac_yandex?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zxcv1234